### Julia for Data Science

#### Julia Code

In [1]:
v = [1,2,3,4,5]
M = [1 2;3 4]
A = [i*j for i in 1:3, j in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

In [2]:
print(A)

[1 2 3; 2 4 6; 3 6 9]

In [1]:
# Tuple
t = (1, "hello", 3.14)

# Dictionary
d = Dict("name" => "Julia", "version" => 1.9)


Dict{String, Any} with 2 entries:
  "name"    => "Julia"
  "version" => 1.9

In [2]:
using DataFrames

df = DataFrame(Name=["Alice", "Bob"],
               Age=[25, 30])

select(df, :Name)
filter(:Age => >(26), df)


1×2 DataFrame
 Row │ Name    Age   
     │ String  Int64 
─────┼───────────────
   1 │ Bob        30

In [3]:
for i in 1:5
  println(i)
end

1
2
3
4
5


#### Python Code

In [1]:
import numpy as np

v = np.array([1, 2, 3, 4, 5])

M = np.array([[1, 2], [3, 4]])

A = np.array([[i*j for j in range(1,4)] for i in range(1,4)]) #Note the indexing

In [2]:
print(A)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [8]:
# Tuple
t = (1, "hello", 3.9)

# Dictionary
d = {"name": "Python", "version": 3.9}


In [9]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Age": [25, 30]
})

df[["Name"]]
df[df["Age"] > 26]


Name  Age
1  Bob   30

In [10]:
for i in range(1,6):
  print(i)

1
2
3
4
5


#### R Code

In [2]:
v <- c(1, 2, 3, 4, 5)

M <- matrix(c(1, 2, 3, 4), nrow = 2, byrow = TRUE)

A <- outer(1:3, 1:3, "*")

In [3]:
print(A)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    4    6
[3,]    3    6    9


In [4]:
# Tuple (R uses a list for heterogeneous types)
t <- list(1, "hello", 3.14)

# Dictionary (use a named list)
d <- list(name = "R", version = 4.4)


In [5]:
 # Base R
df <- data.frame(Name = c("Alice", "Bob"),
                 Age = c(25, 30))

df["Name"]
df[df$Age > 26, ]


In [6]:
library(dplyr)
 df %>% select(Name)
df %>% filter(Age > 26)


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



  Name Age
1  Bob  30

In [7]:
for (i in 1:5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
